name: Mypy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    name: Mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: mypy
      run: |
        mypy .

